INSERT INTO skill(skillId, skillName)VALUES (1, 'HTML');
INSERT INTO skill(skillId, skillName)VALUES (2, 'Bootstrap');
INSERT INTO skill(skillId, skillName)VALUES (3, 'jQuery');
INSERT INTO skill(skillId, skillName)VALUES (4, 'PHP');
INSERT INTO skill(skillId, skillName)VALUES (5, 'MySQL');
INSERT INTO skill(skillId, skillName)VALUES (6, 'JavaScript');
INSERT INTO skill(skillId, skillName)VALUES (7, 'AJAX');
INSERT INTO skill(skillId, skillName)VALUES (8, 'OOP');
INSERT INTO skill(skillId, skillName)VALUES (9, 'Angular');
INSERT INTO skill(skillId, skillName)VALUES (10, 'Java');
INSERT INTO skill(skillId, skillName)VALUES (11, '.NET');
INSERT INTO skill(skillId, skillName)VALUES (12, 'Android');
INSERT INTO skill(skillId, skillName)VALUES (13, 'Organization');
INSERT INTO skill(skillId, skillName)VALUES (14, 'Time Management');
INSERT INTO skill(skillId, skillName)VALUES (15, 'CSS');
INSERT INTO skill(skillId, skillName)VALUES (16, 'Soft Skills (unicorns and rainbows)');
